language: python
python:
  - "2.7"
  - "3.4"

install:
  - "pip install see"
  - "python setup.py install"

script:
  - "python -c 'import mingener'"
  - "python -c 'import mingener; from see import see; print(repr(see(mingener)))'"
  - "python test_countdown.py"
  - "python test_counterdowner.py"
