language: python
python: "2.7"
install:
  - "pip install see"
  - "python setup.py install"
script:
  - "python -c 'import mingener'"
  - "python -c 'import mingener; from see import see; see(mingener)'"
  - "python test_countdown.py"
